{
 "title": "AKA ES Nginx Logs",
 "description": "Completed by Shenxiang, Qingkong and Ruixi",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "label": "domain name",
    "query": "{\"find\":\"terms\",\"field\":\"domain.keyword\"}"
   },
   {
    "name": "status",
    "label": "status code",
    "query": "{\"find\":\"terms\",\"field\":\"status\"}"
   },
   { "name": "responsetime", "label": "request time", "query": "1,2,3,4,5,10" },
   {
    "name": "inter",
    "label": "cycle",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Access PV (relative)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Access UVs (Relative)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "client_ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain Average Response Time (relative)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "responsetime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "domain:$domain",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Basic profile (relative)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "domain.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "client_ip.keyword",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "responsetime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "upstreamtime",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "domain:$domain AND status:$status",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TOP 10",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$domain mobile terminal TOP 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ua.device.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain browser TOP 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ua.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain system TOP 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ua.os_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain => referer top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 18 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "url.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 18 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "upstreamhost.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain HTTP status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "number of status codes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status Code Pie Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API: /ucrmapi/ With Request 200 ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND status:200 AND /ucrmapi/",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API: /ucrmapi/ With Request 200 ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 37 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND 200 AND /ucrmapi/ ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Request 500",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND status:500",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "API With Request 500",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 46 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND 500 AND /ucrmapi/ ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Client Access",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "client_ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain Visit PV today (every 10 minutes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PV and UV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$domain Access PV for 7 days (every 10 minutes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " Historical trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$domain number of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "reqps", "label": "frequency" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": true,
       "id": "1",
       "type": "count"
      },
      {
       "field": "select field",
       "id": "3",
       "meta": {},
       "pipelineVariables": [
        { "name": "qps", "pipelineAgg": "1" }
       ],
       "settings": { "script": "params.qps*1000/$__interval_ms" },
       "type": "bucket_script"
      }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain Proportion of request methods",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_method.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain referer top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "referer.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data report analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$domain => Client data details please",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 88 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_ip.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "url.keyword",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "size",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "domain:$domain AND status:$status",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain => Client data details please",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_ip.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "url.keyword",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "size",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "domain:$domain AND status:$status",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain => Request Url Data details please",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" },
      {
       "field": "clientip.keyword",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "field": "responsetime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "upstreamtime",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "size",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "domain:$domain AND status:$status",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$domain => Nginx log list",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.country_name.keyword",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.region_name.keyword",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.city_name.keyword",
       "id": "11",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "client_ip.keyword",
       "id": "12",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "ua.os_name.keyword",
       "id": "14",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "ua.name.keyword",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "domain.keyword",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "request_method.keyword",
       "id": "18",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "responsetime",
       "id": "19",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "upstreamtime",
       "id": "20",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "status",
       "id": "13",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "domain:$domain AND status:$status",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}